### ISSUE TITLE
Show talents in roll popup

### ISSUE THREAD

**Issue by uhu79** [DrOgres/twdu#10]
it would be great to be notified of talents (or even equipment) that could give a bonus or have an effect on a roll in the roll-popup window

**Comment by DrOgres** [comment]
This already happens if a talent or piece of gear has a potential impact on a given skill it will add a pull-down to the roll dialog 
![talent-roll](https://github.com/DrOgres/twdu/assets/74268782/b525eb22-9d82-4946-a18a-8cc8c441c51b)

Selecting from that pull-down will add the appropriate number of dice to the pool

 
![fixer-selected](https://github.com/DrOgres/twdu/assets/74268782/54f0901c-0821-4eca-981c-b97c1cf24009)

![rollresult](https://github.com/DrOgres/twdu/assets/74268782/361a7ffe-c704-485d-9d50-02d8ccec6caa)

**Comment by uhu79** [comment]
my bad, I am playing solo and have used gear on an NPC where it does not have an effect I have just found

and I was using a talent like "right word at the right time" that gives you an extra success when you succeed but does not add dice to the roll - and I was constantly forgetting to apply that talent, so was wondering if a reminder could be integrated like (remember, you got a talent for that skill)

**Comment by uhu79** [comment]
but... thinking about it - NPCs can use weapons so they should also be able to use gear - the rules do not say anything about it though

**Comment by DrOgres** [comment]
hmm I'll re-read the rules, in the back of my head NPC's don't get talents or gear bonuses. I could be hallucinating, but I'll re-read and align things to RAW either way.

**Comment by uhu79** [comment]
page 29 "NPCs don’t have attributes, skills, or talents."

page 118 "If there is an NPC in the campaign that you think needs special attention, maybe because the NPC is an important part of the endgame, you could give them attributes, skill levels, and even talents."

does not say anything about gear though - but armor and weapons should definitely be applied (and if only for damage) 

and I would argue as should a bonus from a medkit. at least I would absolutely insist as PC that the NPC doc gets the bonus when fixing me :-)

so not sure if this is a case of RAW, more of RAI

from what I read you should also remove weapon bonus from NPCs because it says nowhere that this is applied either

**Comment by uhu79** [comment]
addon: the talent "Skullcracker" is not shown in the dropdown

**Comment by DrOgres** [comment]
This is fixed in the Next update

**Comment by DrOgres** [comment]
v1.0.3 released with this fix in it
